### ISSUE TITLE
npx electron-builder

### ISSUE THREAD

**Issue by Antre-dev** [MainSilent/linux.js#6]
when i type npx electron-builder in the terminal i get this error:Error: Cannot find module 'fs/promises'
Require stack:
- /home/antos20dev/Documents/ANTOS2.0DEV/node_modules/builder-util/out/fs.js
- /home/antos20dev/Documents/ANTOS2.0DEV/node_modules/builder-util/out/util.js
- /home/antos20dev/Documents/ANTOS2.0DEV/node_modules/electron-builder/out/cli/cli.js
- /home/antos20dev/Documents/ANTOS2.0DEV/node_modules/electron-builder/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/antos20dev/Documents/ANTOS2.0DEV/node_modules/builder-util/src/fs.ts:5:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/antos20dev/Documents/ANTOS2.0DEV/node_modules/builder-util/src/util.ts:25:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)

pls help

**Comment by Antre-dev** [comment]
fixed you need to update node js
